{% set version = "4021.83" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fmultivar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fMultivar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fMultivar/fMultivar_{{ version }}.tar.gz
  sha256: cd30259c1386ba21c4030c77a6fcbc740fe4c788f0053d8bed5e44e9e1174b26

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cubature
    - r-fbasics
    - r-mvtnorm
    - r-sn
  run:
    - r-base
    - r-cubature
    - r-fbasics
    - r-mvtnorm
    - r-sn

test:
  commands:
    - $R -e "library('fMultivar')"           # [not win]
    - "\"%R%\" -e \"library('fMultivar')\""  # [win]

about:
  home: https://www.rmetrics.org
  license: GPL-2.0-or-later
  summary: Provides a  collection of functions to manage, to investigate and to analyze bivariate and multivariate data sets of financial returns.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - zdk123

# Package: fMultivar
# Title: Rmetrics - Analysing and Modeling Multivariate Financial Return Distributions
# Date: 2017-11-12
# Version: 3042.80.1
# Author: Diethelm Wuertz [aut], Tobias Setz [cre], Yohan Chalabi [ctb]
# Maintainer: Tobias Setz <tobias.setz@live.com>
# Description: Provides a  collection of functions to manage, to investigate and to analyze bivariate and multivariate data sets of financial returns.
# Depends: R (>= 2.15.1), timeDate, timeSeries, fBasics
# Imports: cubature, mvtnorm, sn, methods, grDevices, graphics, stats
# Suggests: spatial, RUnit, tcltk, akima
# LazyData: yes
# License: GPL (>= 2)
# URL: https://www.rmetrics.org
# NeedsCompilation: no
# Packaged: 2020-03-07 10:25:30 UTC; hornik
# Repository: CRAN
# Date/Publication: 2020-03-07 11:06:19 UTC
